### ISSUE TITLE
error about MYSQL server

### ISSUE THREAD

**Issue by ZhuoxinChen** [Biobix/proBAMconvert#6]
ERROR:(2005, "Unknown MySQL server host 'ensembldb.ensembl.org' (0)")
Please check if all parameters were supplied correctly, if the error keeps occuring contact the developers at "https://github.com/Biobix/proBAMconvert/issues" and provide the file to be processed along with the following error message:
(2005, "Unknown MySQL server host 'ensembldb.ensembl.org' (0)")

**Comment by vladie0** [comment]
Dear ZhuoxinChen, 

It seems that proBAMconvert is unable to connect to the Ensembl database servers. Could you provide me with some additional information:
What system you are working on and are using proBAMconvert on a private network? ( It might be that some private instances do not allow connection to "foreign" ports.

Also, A new proBAMconvert version has been released today, could you check whether this error reoccurs on the new version ? 

Thank you

**Comment by vladie0** [comment]
I will close this issue and assume that the issue has been resolved with the newest proBAMconvert version for now
