### ISSUE TITLE
proBAMconvert interruption 

### ISSUE THREAD

**Issue by KaiLiCn** [Biobix/proBAMconvert#7]
Hi:

When I converted one mzIdentML file to proBAM, I met one error as follow.
"ERROR:'ascii' codec can't encode characters in position 8-11: ordinal not in range(128)"

I wish you can fix it.

Best regards!

Kai

**Comment by vladie0** [comment]
Hello JaiLiCn,

Thank you for reporting this issue, before I can proceed to solve this question I would need to ask you a couple of thinks:

Which operating system were you using ? 
What version of proBAMconvert did you use ? (GUI, commandline, galaxy)?
It looks like proBAMconvert fails to read a certain part of the mzIdentML, some software tend to output the mzIdentML slightly different rendering proBAMconvert unable to read the file correctly. Can you tell me what software was used to generate the corresponding file and, if possible, provide me with the corresponding mzIdentML file. This way I can solve the issue and add it to the list of exceptions.

Best Regards,
Volodimir Olexiouk

**Comment by KaiLiCn** [comment]
Hi Volodimir Olexiouk,

Thanks for your reply. 

The mzIdentML file was generated by "MSGF+" and I ran proBAMConvert v1.0.1 on windows.  How can I send you the file? May I send it by email?

Best Regards!
Kai

**Comment by vladie0** [comment]
Hi Kai, 

If you could upload your file in the following dropbox directory it would be great: 
https://www.dropbox.com/sh/bv4yi2incyzna02/AACQeooY0DQONZEj4k3PzKCha?dl=0

Sorry for the trouble,
Volodimir Olexiouk

**Comment by KaiLiCn** [comment]
Hi Volodimir Olexiouk,

I am sorry to tell you that I couldn't upload file in your link. But I uploaded it on my dropbox, may I share the link with you by email?

Kai

**Comment by vladie0** [comment]
Hi Kai, 

Sure, my email: volodimir.olexiouk@ugent.be

thank you

**Comment by vladie0** [comment]
Apologies for getting back to you this late, 

I've investigated the file, first of all I would like to ask what parameters you've used for proBAMconvert ? 
I've noticed that the identified proteins are from Chlorocebus sabaeus, currently proBAMconvert support human,mouse,fruitfly,zebrafish.

I could add support for for the species of interest if that would be favorably
